Add option -nostdlib for preventing linker from complaining
Since Ubuntu 16.04, it enables the stack protection by default which
causes undefined reference to __stack_chk_guard error.